# Generated by Django 4.1.3 on 2022-12-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_brand_producttype_product_brand_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='product/'),
        ),
    ]
