# Generated by Django 4.1.3 on 2023-04-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_pagecategory_options_pagecategory_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pages',
            new_name='Page',
        ),
        migrations.AlterField(
            model_name='pagecategory',
            name='url',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
