# Generated by Django 4.1.3 on 2023-04-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_pages_page_alter_pagecategory_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='pagecategory',
            name='url',
            field=models.SlugField(blank=True, default='', null=True, unique=True),
        ),
    ]
