# Generated by Django 4.1.3 on 2023-04-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_page_url_alter_pagecategory_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='pagecategory',
            name='url',
            field=models.SlugField(default='', unique=True),
        ),
    ]
