# Generated by Django 4.1.3 on 2023-05-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_deliverytype_paymenttype_order_delivery_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='art_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cranking_amperage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='polarity',
            field=models.CharField(blank=True, choices=[('REV', 'Обратная'), ('DIR', 'Прямая'), ('UNI', 'Универсальная')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='voltage',
            field=models.IntegerField(blank=True, default=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.IntegerField(blank=True, default=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
