# Generated by Django 4.2.1 on 2023-07-14 19:37

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_slug_alter_product_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to=store.models.get_upload_path),
        ),
    ]
