version: '3.8'
services:

  redis:
    container_name: redis
    image: redis:alpine

  app:
    restart: always
    volumes:
      - static:/vol/web
    ports:
      - "8000:8000"
    container_name: app
    image: cr.yandex/{{ env.CR_REGISTRY }}/{{ env.CR_REPOSITORY }}:app-{{ env.IMAGE_TAG }}
    environment:
      - DEBUG=False
      - SECRET_KEY={{env.SECRET_KEY}}
      - DB_ENGINE={{env.DB_ENGINE}}
      - DB_HOST=db
      - DB_NAME=main_db
      - DB_USER={{env.DB_USER}}
      - DB_PASSWORD={{env.DB_PASSWORD}}
      - DJANGO_ALLOWED_HOSTS={{env.DJANGO_ALLOWED_HOSTS}}
      - CSRF_TRUSTED_ORIGINS={{env.CSRF_TRUSTED_ORIGINS}}
      - AWS_S3_ACCESS_KEY_ID={{env.AWS_S3_ACCESS_KEY_ID}}
      - AWS_S3_SECRET_ACCESS_KEY={{env.AWS_S3_SECRET_ACCESS_KEY}}
      - GOODS_FEED_URL={{env.GOODS_FEED_URL}}
      - EMAIL_HOST={{env.EMAIL_HOST}}
      - EMAIL_HOST_USER={{env.EMAIL_HOST_USER}}
      - EMAIL_HOST_PASSWORD={{env.EMAIL_HOST_PASSWORD}}
      - MANAGERS_EMAILS={{env.MANAGERS_EMAILS}}
      - DEFAULT_FROM_EMAIL={{env.DEFAULT_FROM_EMAIL}}
    depends_on:
      - db
      - redis
  
  db:
    image: postgres:13-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=main_db
      - POSTGRES_USER={{env.DB_USER}}
      - POSTGRES_PASSWORD={{env.DB_PASSWORD}}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  proxy:
    container_name: proxy
    image: cr.yandex/{{ env.CR_REGISTRY }}/{{ env.CR_REPOSITORY }}:proxy-{{ env.IMAGE_TAG }}
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/vol/web
      - certbot-web:/vol/www
      - proxy-dhparams:/vol/proxy
      - certbot-certs:/etc/letsencrypt
    environment:
      - DOMAIN={{env.DOMAIN}}

  certbot:
    container_name: certbot
    image: cr.yandex/{{ env.CR_REGISTRY }}/{{ env.CR_REPOSITORY }}:certbot-{{ env.IMAGE_TAG }}
    #command: sh /opt/certify-init.sh // Only for the first run
    environment:
      - EMAIL={{env.ACME_DEFAULT_EMAIL}}
      - DOMAIN={{env.DOMAIN}}
    volumes:
      - certbot-web:/vol/www
      - certbot-certs:/etc/letsencrypt
    depends_on:
      - proxy

  celeryworker:
    container_name: celeryworker
    image: cr.yandex/{{ env.CR_REGISTRY }}/{{ env.CR_REPOSITORY }}:app-{{ env.IMAGE_TAG }}
    restart: on-failure
    environment:
      - BROKER_URL=${BROKER_URL}
      - CELERY_BACKEND=${BROKER_URL}
      - CELERY_BROKER=${BROKER_URL}
    depends_on:
      - app
    command: 'celery -A ecomm1 worker -l DEBUG'
    volumes:
      - static:/vol/web

  celerybeat:
    container_name: celerybeat
    image: cr.yandex/{{ env.CR_REGISTRY }}/{{ env.CR_REPOSITORY }}:app-{{ env.IMAGE_TAG }}
    restart: on-failure
    environment:
      - BROKER_URL=${BROKER_URL}
      - CELERY_BACKEND=${BROKER_URL}
      - CELERY_BROKER=${BROKER_URL}
    depends_on:
      - app
      - celeryworker
    command: 'celery -A ecomm1 beat'
    volumes:
      - static:/vol/web

volumes:
  postgres-data:
  static:
  certbot-web:
  proxy-dhparams:
  certbot-certs:

